name: Release
on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml
  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: ./.github/actions/setup-test-env
      - name: Update npm to latest
        run: npm install -g npm@latest
      - name: Publish requirefire to npm
        run: npm publish --access public
      - name: Get version
        id: version
        run: echo "version=$(node -p 'require(\"./package.json\").version')" >> "$GITHUB_OUTPUT"
      - name: Publish Release to github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
