name: "Test"
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [16, 18, 20]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/setup-test-env
      - name: Test
        shell: bash
        run: pnpm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/setup-test-env
      - name: Lint
        shell: bash
        run: pnpm lint

  build-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./.github/actions/setup-test-env
      - name: Build
        shell: bash
        run: pnpm build
